# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('valide', models.BooleanField()),
                ('solde', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_employe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('id_employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Commercant')),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='id_employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employeur'),
        ),
        migrations.AddField(
            model_name='employe',
            name='num_carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Carte'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
