# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_carte_num_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='date_expiration',
            field=models.DateTimeField(),
        ),
    ]
