# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_auto_20170314_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='solde',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='montant_employe',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
