# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='id_employe',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employe'),
        ),
    ]
