# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0008_recharge_id_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_employe', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField()),
                ('id_employe', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employe')),
                ('id_employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverapp.Employeur')),
            ],
        ),
    ]
